// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	model "github.com/OurLuv/prefood/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockFoodService is a mock of FoodService interface.
type MockFoodService struct {
	ctrl     *gomock.Controller
	recorder *MockFoodServiceMockRecorder
}

// MockFoodServiceMockRecorder is the mock recorder for MockFoodService.
type MockFoodServiceMockRecorder struct {
	mock *MockFoodService
}

// NewMockFoodService creates a new mock instance.
func NewMockFoodService(ctrl *gomock.Controller) *MockFoodService {
	mock := &MockFoodService{ctrl: ctrl}
	mock.recorder = &MockFoodServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoodService) EXPECT() *MockFoodServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFoodService) Create(c model.Food) (*model.Food, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c)
	ret0, _ := ret[0].(*model.Food)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFoodServiceMockRecorder) Create(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFoodService)(nil).Create), c)
}

// DeleteById mocks base method.
func (m *MockFoodService) DeleteById(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockFoodServiceMockRecorder) DeleteById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockFoodService)(nil).DeleteById), id)
}

// GetAll mocks base method.
func (m *MockFoodService) GetAll(id uint) ([]model.Food, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", id)
	ret0, _ := ret[0].([]model.Food)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockFoodServiceMockRecorder) GetAll(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockFoodService)(nil).GetAll), id)
}

// GetById mocks base method.
func (m *MockFoodService) GetById(restaurantId, id uint) (*model.Food, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", restaurantId, id)
	ret0, _ := ret[0].(*model.Food)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockFoodServiceMockRecorder) GetById(restaurantId, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockFoodService)(nil).GetById), restaurantId, id)
}

// UpdateById mocks base method.
func (m *MockFoodService) UpdateById(c model.Food) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateById", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateById indicates an expected call of UpdateById.
func (mr *MockFoodServiceMockRecorder) UpdateById(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateById", reflect.TypeOf((*MockFoodService)(nil).UpdateById), c)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// CheckForEmail mocks base method.
func (m *MockUserService) CheckForEmail(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForEmail", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckForEmail indicates an expected call of CheckForEmail.
func (mr *MockUserServiceMockRecorder) CheckForEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForEmail", reflect.TypeOf((*MockUserService)(nil).CheckForEmail), email)
}

// Create mocks base method.
func (m *MockUserService) Create(u model.User) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", u)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserServiceMockRecorder) Create(u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserService)(nil).Create), u)
}

// DeleteById mocks base method.
func (m *MockUserService) DeleteById(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockUserServiceMockRecorder) DeleteById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockUserService)(nil).DeleteById), id)
}

// GetById mocks base method.
func (m *MockUserService) GetById(id uint) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockUserServiceMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockUserService)(nil).GetById), id)
}

// Login mocks base method.
func (m *MockUserService) Login(email, password string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", email, password)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceMockRecorder) Login(email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserService)(nil).Login), email, password)
}

// UpdateById mocks base method.
func (m *MockUserService) UpdateById(id uint, c model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateById", id, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateById indicates an expected call of UpdateById.
func (mr *MockUserServiceMockRecorder) UpdateById(id, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateById", reflect.TypeOf((*MockUserService)(nil).UpdateById), id, c)
}
